name: Lint

on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Fixed ESLint
        run: yarn lint --fix

      - name: Test ESLint
        run: yarn lint
        env:
          Lint: true
